sudo: required
services: 
  - docker

before_install:
  - docker build -t joshuaaguilar20/react -f Dockerfile.dev .

script:
  - docker run joshuaaguilar20/react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "Docker-React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-994900725875"
  bucket_path: "Docker-React"
  on:
   branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
     secure: "$AWS_SECRET_KEY"


