
export const SEND_BFSCRIPT = 'SEND_BFSCRIPT';
export const PREVIOUS_STATE = "PREVIOUS_STATE";
export const FETCH_STREAMS = 'FETCH_STREAMS';
export const FETCH_STREAM = 'FETCH_STREAM';
export const DELETE_STREAM = 'DELETE_STREAM';
export const EDIT_STREAM = 'EDIT_STREAM';
